version: 0.0
os: linux

files:
  - source: files/index.html
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: index.html
    owner: apache
    group: apache
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
    - location: scritps/delete-old-index.sh
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/sleep.sh
    - location: scripts/webserver-start.sh
